package(default_visibility = ["//visibility:public"])

cc_library(
    name = "tier_flow",
    hdrs = [
        "tier_flow_recorder.h",
    ],
    deps = [
        "//kv_cache_manager/optimizer/config",
    ],
)
